api_platform:
    defaults:
        pagination_client_items_per_page: true
    collection:
        pagination:
            items_per_page: 3
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    http_cache:
        public: ~

        invalidation:
            enabled: false
            varnish_urls: [ ]
            request_options: [ ]

        etag: true

        max_age: 3600

        shared_max_age: 3600

        vary: [ 'Accept' ]